creation_rules:
  - path_regex: secrets/secrets\.ya?ml$
    age: >-
      age1g22zadurycv2jl0a4pl8ye53rqpxxktnscmgmhxwpk90kaf5qsystgmq39,
      age15cwvfwf2z878szwt0q42e73mfcefh96mnylewhh5u5gmlvst45pqvus373
