[tools]
node = "22"
ruby = "3.1.2"
python = "3.10.20"
java = "zulu-17"
bun = "latest"
go = "1.25.3"
fzf = "0.59.0"
pnpm = "latest"
sops = "latest"
age = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
