[tools]
node = "24"
ruby = "3.1.2"
python = "3.14.5"
rust = "1.93.1"
java = "zulu-17"
bun = "latest"
go = "1.25.3"
fzf = "0.59.0"
pnpm = "latest"
sops = "latest"
age = "latest"
terraform = "latest"
kubectl = "latest"
gh = "latest"
glab = "latest"
just = "latest"
lefthook = "latest"
"npm:@agentclientprotocol/claude-agent-acp" = "latest"
"npm:agent-browser" = "latest"
"npm:firebase-tools" = "latest"
"npm:rn-logs-cli" = "latest"
"npm:wrangler" = "latest"
"github:stripe/stripe-cli" = "latest"
"aqua:hashicorp/vault" = "2.0.2"
railway = { version = "latest", exe = "railway" }
"npm:typescript-language-server" = "latest"
"npm:agent-device" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"aqua:charmbracelet/vhs" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
