#!/bin/bash

# template for automatically creating a tmux session
 
function tmux-app-session
{
    BASE="$HOME/basedir"
    cd $BASE
 
    tmux start-server
    tmux kill-session -t app
    tmux new-session -d -s app -n root
    tmux new-window -t app:2 -n framework
    tmux new-window -t app:3 -n tests
    tmux new-window -t app:4 -n app
 
    tmux send-keys -t app:2 "cd $BASE/framework" C-m
    tmux send-keys -t app:3 "cd $BASE/tests/unit" C-m
    tmux split-window -t app:3 -v
    tmux send-keys -t app:3 "cd $BASE/tests/functional" C-m
    tmux send-keys -t app:4 "cd $BASE/app" C-m
 
    tmux select-window -t app:1
    tmux attach-session -t app
}

tmux-app-session

